#!/usr/bin/env node
/**
 * sync-shared.mjs — copy canonical shared hook utilities from
 * packages/hooks-shared/src/ into each consumer plugin's
 * scripts/_shared/ directory.
 *
 * Claude Code plugins are distributed as self-contained directories;
 * the marketplace installer does not run `npm install` or resolve
 * sibling-plugin imports, so shared code is physically copied into
 * each plugin that consumes it.
 *
 * This script reads the consumer manifest below, wipes each plugin's
 * _shared/ directory, and re-copies exactly the files the plugin
 * declares. Every copy is byte-identical to the canonical source.
 * Run `pnpm run verify-shared` afterwards (or in CI) to prove it.
 *
 * Also writes a SYNC_SOURCE file into each _shared/ directory — a
 * breadcrumb so anyone who stumbles on a synced copy knows where the
 * real source lives and that manual edits will be overwritten.
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

import { CONSUMERS } from "./consumer-manifest.mjs";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, "..");
const SRC_DIR = path.join(REPO_ROOT, "packages", "hooks-shared", "src");

const SYNC_SOURCE_BANNER = `This directory is regenerated by \`pnpm run sync-shared\`.
Canonical source: packages/hooks-shared/src/
Do NOT edit files here directly — run sync-shared after editing the source.
`;

function rmDirContents(dir) {
  if (!fs.existsSync(dir)) return;
  for (const name of fs.readdirSync(dir)) {
    fs.rmSync(path.join(dir, name), { recursive: true, force: true });
  }
}

function main() {
  for (const { plugin, modules } of CONSUMERS) {
    const dest = path.join(
      REPO_ROOT,
      "plugins",
      plugin,
      "scripts",
      "_shared"
    );
    fs.mkdirSync(dest, { recursive: true });
    rmDirContents(dest);

    for (const mod of modules) {
      const from = path.join(SRC_DIR, mod);
      const to = path.join(dest, mod);
      if (!fs.existsSync(from)) {
        console.error(`Missing canonical source: ${path.relative(REPO_ROOT, from)}`);
        process.exit(1);
      }
      fs.copyFileSync(from, to);
    }

    fs.writeFileSync(path.join(dest, "SYNC_SOURCE"), SYNC_SOURCE_BANNER);

    console.log(
      `synced ${modules.length} file(s) → plugins/${plugin}/scripts/_shared/`
    );
  }
}

main();
